# MTJ Build Properties
KEmulator.includes=src\
,res\
,gllib/ASprite.java\
,gllib/BuyCloseTask.java\
,gllib/BuyTask.java\
,gllib/PaySMS.java\
,gllib/GLLib.java\
,gllib/GLLibImage.java\
,gllib/GLLibPathFinding.java\
,gllib/GLLibPlayer.java\
,gllib/HTTP.java\
,gllib/IGP.java\
,gllib/PlatformRequestWorker.java\

KEmulator.excludes=\

